apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-project-two
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: project-two
  source:
    path: manifests/development/project-two/
    repoURL: https://github.com/albmtez/argocd-declarative-template.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
