apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: root
  sources:
  - path: app-configs/development/config/
    repoURL: https://github.com/albmtez/argocd-declarative-template.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
